services:
  frontend:
    image: ghcr.io/wims-org/wims-frontend:dev
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    image: ghcr.io/wims-org/wims-backend:dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - wims-data:/data # file/image asset path (optional)
    environment:
      - LOG_LEVEL=INFO
      - SEND_TELEMETRY=False
      - DATABASE_URI=mysql+aiomysql://root:example@db:3306/wims
      - FEATURES_OPENAI_API_KEY=sthsth
      - SENTRY_DSN_BACKEND=https://9f6b292159894c6983b61313779ad123@glitch.fleaz.me/4
      - SENTRY_DSN_FRONTEND=https://08b94672614847df87cac87c393f4a66@glitch.fleaz.me/5
      - RUN_MODE=production
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wims
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mariadb-data:
  wims-data:
