services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/src/data:/data
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend

  frontend:
    image: kailus.dev/wims-org/wims-frontend:dev
    build: ./vue_frontend
    depends_on:
      - backend

  backend:
    image: kailus.dev/wims-org/wims-backend:dev
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./docker/config.default.yml:/app/src/config.yml:ro
      - ./docker/data/categories.json:/app/data/categories.json:ro
    environment:
      - LOG_LEVEL=INFO
      - DATABASE_URI=mysql+aiomysql://root:example@db:3306/wims
      - FEATURES_OPENAI_API_KEY=sthsth
      - SENTRY_DSN="https://9f6b292159894c6983b61313779ad123@glitch.fleaz.me/4"
      - RUN_MODE=production

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_USER: root 
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wims


volumes:
  mariadb-data:
  mongodb-data: