services:
  frontend:
    image: kailus.dev/wims-org/wims-frontend:dev
    build: ./vue_frontend
    depends_on:
      - backend

  backend:
    image: kailus.dev/wims-org/wims-backend:dev
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./docker/config.default.yml:/app/src/config.yml:ro
      - ./docker/data/categories.json:/app/data/categories.json:ro
    environment:
      - LOG_LEVEL=INFO
      - DATABASE_URI=mysql+aiomysql://root:example@db:3306/wims
      - FEATURES_OPENAI_API_KEY=sthsth
      - SENTRY_DSN=https://9f6b292159894c6983b61313779ad123@glitch.fleaz.me/4
      - RUN_MODE=production
    ports:
      - "8000:8000"
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wims
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mariadb-data:
  mongodb-data:
