/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrayField: typeof import('./src/components/fields/ArrayField.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInput: typeof import('bootstrap-vue-next/components/BFormInput')['BInput']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    CheckboxField: typeof import('./src/components/fields/CheckboxField.vue')['default']
    ContainerListComponent: typeof import('./src/components/shared/ContainerListComponent.vue')['default']
    ImageModal: typeof import('./src/components/shared/ImageModal.vue')['default']
    ImageThumbnailField: typeof import('./src/components/fields/ImageThumbnailField.vue')['default']
    ItemComparison: typeof import('./src/components/ItemComparison.vue')['default']
    ItemField: typeof import('./src/components/fields/ItemField.vue')['default']
    ItemForm: typeof import('./src/components/ItemForm.vue')['default']
    ItemList: typeof import('./src/components/ItemList.vue')['default']
    ItemsFormList: typeof import('./src/components/ItemsFormList.vue')['default']
    LLMCompletion: typeof import('./src/components/LLMCompletion.vue')['default']
    LoadingField: typeof import('./src/components/fields/LoadingField.vue')['default']
    ModalField: typeof import('./src/components/fields/ModalField.vue')['default']
    NumberField: typeof import('./src/components/fields/NumberField.vue')['default']
    ObjectField: typeof import('./src/components/fields/ObjectField.vue')['default']
    QueryEditor: typeof import('./src/components/shared/QueryEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/shared/SearchComponent.vue')['default']
    SearchModal: typeof import('./src/components/shared/SearchModal.vue')['default']
    TextAreaField: typeof import('./src/components/fields/TextAreaField.vue')['default']
    TextField: typeof import('./src/components/fields/TextField.vue')['default']
    TitleComponent: typeof import('./src/components/TitleComponent.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
