/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Users */
        get: operations["get_all_users_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_users__id__get"];
        /** Update User */
        put: operations["update_user_users__id__put"];
        post?: never;
        /** Delete User */
        delete: operations["delete_user_users__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Item */
        post: operations["create_item_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Backlog Item */
        post: operations["create_backlog_item_items_backlog_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_items__id__get"];
        /** Update Item */
        put: operations["update_item_items__id__put"];
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_items__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Item */
        get: operations["get_all_item_items__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item With Containers */
        get: operations["get_item_with_containers_items__id__containers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Item Search
         * @description Search for items based on a query object, post to allow for body.
         */
        post: operations["get_item_search_items_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readers */
        get: operations["get_readers_readers_get"];
        put?: never;
        /** Create Reader */
        post: operations["create_reader_readers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readers/{reader_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Reader */
        get: operations["read_reader_readers__reader_id__get"];
        put?: never;
        post?: never;
        /** Delete Reader */
        delete: operations["delete_reader_readers__reader_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_config__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Message Stream */
        get: operations["message_stream_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Subscription */
        post: operations["add_subscription_stream_subscription_post"];
        /** Delete Subscription */
        delete: operations["delete_subscription_stream_subscription_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Event */
        post: operations["scan_event_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigResponseModel */
        ConfigResponseModel: {
            /** Llm Enabled */
            llm_enabled: boolean;
        };
        /** ContainerObject */
        ContainerObject: {
            /** Item Id */
            item_id: number;
            /** Short Name */
            short_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagePublic */
        ImagePublic: {
            /** Item Id */
            item_id: number;
        };
        /**
         * ItemBacklog
         * @description This model is used for weaker validation in eg /backlog route
         */
        ItemBacklog: {
            /**
             * Short Name
             * @default New Item
             */
            short_name: string;
            /** Container Id */
            container_id?: number | null;
            /**
             * Is Container
             * @default false
             */
            is_container: boolean;
            /** Tag Uuid */
            tag_uuid: string | null;
            /** Amount */
            amount?: number | null;
            /** Category Id */
            category_id?: number | null;
            /**
             * Consumable
             * @default false
             */
            consumable: boolean;
            /** Description */
            description?: string | null;
            /** Min Amount */
            min_amount?: number | null;
            /** Tags */
            tags?: string[];
            /** Price New */
            price_new?: number | null;
            /** Price Used */
            price_used?: number | null;
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Manufacturing Date */
            manufacturing_date?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Author Id */
            author_id?: number | null;
            /** Borrower Id */
            borrower_id?: number | null;
            /** Borrowed At */
            borrowed_at?: string | null;
            /** Borrowed Until */
            borrowed_until?: string | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** ItemCreate */
        ItemCreate: {
            /** Short Name */
            short_name: string;
            /** Container Id */
            container_id?: number | null;
            /**
             * Is Container
             * @default false
             */
            is_container: boolean;
            /** Tag Uuid */
            tag_uuid: string | null;
            /** Amount */
            amount?: number | null;
            /** Category Id */
            category_id?: number | null;
            /**
             * Consumable
             * @default false
             */
            consumable: boolean;
            /** Description */
            description?: string | null;
            /** Min Amount */
            min_amount?: number | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Price New */
            price_new?: number | null;
            /** Price Used */
            price_used?: number | null;
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Manufacturing Date */
            manufacturing_date?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Author Id */
            author_id?: number | null;
            /** Borrower Id */
            borrower_id?: number | null;
            /** Borrowed At */
            borrowed_at?: string | null;
            /** Borrowed Until */
            borrowed_until?: string | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** ItemPublic */
        ItemPublic: {
            /** Id */
            id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Short Name */
            short_name: string;
            /** Container Id */
            container_id?: number | null;
            /**
             * Is Container
             * @default false
             */
            is_container: boolean;
            /** Tag Uuid */
            tag_uuid: string | null;
            /** Amount */
            amount?: number | null;
            /** Category Id */
            category_id?: number | null;
            /**
             * Consumable
             * @default false
             */
            consumable: boolean;
            /** Description */
            description?: string | null;
            /** Min Amount */
            min_amount?: number | null;
            /** Tags */
            tags?: string[];
            /** Price New */
            price_new?: number | null;
            /** Price Used */
            price_used?: number | null;
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Manufacturing Date */
            manufacturing_date?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Author Id */
            author_id?: number | null;
            /** Borrower Id */
            borrower_id?: number | null;
            /** Borrowed At */
            borrowed_at?: string | null;
            /** Borrowed Until */
            borrowed_until?: string | null;
            /** Owner Id */
            owner_id?: number | null;
            /** Borrowed */
            readonly borrowed: boolean;
        };
        /** ItemPublicWithRefs */
        ItemPublicWithRefs: {
            /** Id */
            id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Short Name */
            short_name: string;
            /** Container Id */
            container_id?: number | null;
            /**
             * Is Container
             * @default false
             */
            is_container: boolean;
            /** Tag Uuid */
            tag_uuid: string | null;
            /** Amount */
            amount?: number | null;
            /** Category Id */
            category_id?: number | null;
            /**
             * Consumable
             * @default false
             */
            consumable: boolean;
            /** Description */
            description?: string | null;
            /** Min Amount */
            min_amount?: number | null;
            /** Tags */
            tags?: string[];
            /** Price New */
            price_new?: number | null;
            /** Price Used */
            price_used?: number | null;
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Manufacturing Date */
            manufacturing_date?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Author Id */
            author_id?: number | null;
            /** Borrower Id */
            borrower_id?: number | null;
            /** Borrowed At */
            borrowed_at?: string | null;
            /** Borrowed Until */
            borrowed_until?: string | null;
            /** Owner Id */
            owner_id?: number | null;
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ImagePublic"][];
            author?: components["schemas"]["UserPublic"] | null;
            borrower?: components["schemas"]["UserPublic"] | null;
            owner?: components["schemas"]["UserPublic"] | null;
            /**
             * Urls
             * @default []
             */
            urls: components["schemas"]["UrlPublic"][];
            container?: components["schemas"]["ItemPublic"] | null;
        };
        /** ItemUpdate */
        ItemUpdate: {
            /** Short Name */
            short_name: string;
            /** Container Id */
            container_id?: number | null;
            /**
             * Is Container
             * @default false
             */
            is_container: boolean;
            /** Tag Uuid */
            tag_uuid: string | null;
            /** Amount */
            amount?: number | null;
            /** Category Id */
            category_id?: number | null;
            /**
             * Consumable
             * @default false
             */
            consumable: boolean;
            /** Description */
            description?: string | null;
            /** Min Amount */
            min_amount?: number | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Price New */
            price_new?: number | null;
            /** Price Used */
            price_used?: number | null;
            /** Acquisition Date */
            acquisition_date?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Manufacturing Date */
            manufacturing_date?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Author Id */
            author_id?: number | null;
            /** Borrower Id */
            borrower_id?: number | null;
            /** Borrowed At */
            borrowed_at?: string | null;
            /** Borrowed Until */
            borrowed_until?: string | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** Query */
        Query: {
            /** Term */
            term?: string | null;
            /**
             * Filters
             * @default {}
             */
            filters: {
                [key: string]: string;
            };
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Sort By */
            sort_by?: string | null;
            /**
             * Sort Desc
             * @default false
             */
            sort_desc: boolean;
        };
        /** ReaderCreate */
        ReaderCreate: {
            /** Reader Id */
            reader_id: string;
            /** Reader Name */
            reader_name?: string;
        };
        /** ReaderPublic */
        ReaderPublic: {
            /** Id */
            id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Reader Id */
            reader_id: string;
            /** Reader Name */
            reader_name?: string;
        };
        /** ScanRequest */
        ScanRequest: {
            /** Reader Id */
            reader_id: string;
            /** Tag Id */
            tag_id: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | string | unknown;
        };
        /** ScanResponse */
        ScanResponse: {
            /** Msg */
            msg: string;
            /** Item Name */
            item_name: string;
            /** Item Storage Location */
            item_storage_location: string;
        };
        /** StreamRequestData */
        StreamRequestData: {
            /** Stream Id */
            stream_id: string;
            /** Reader Id */
            reader_id?: string | null;
        };
        /** UrlPublic */
        UrlPublic: {
            /** Item Id */
            item_id: number;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
        };
        /** UserPublic */
        UserPublic: {
            /** Id */
            id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_all_users_users_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_backlog_item_items_backlog_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemBacklog"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_items__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublicWithRefs"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_items__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_items__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_item_items__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_with_containers_items__id__containers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerObject"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_search_items_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Query"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_readers_readers_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderPublic"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reader_readers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReaderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderPublic"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_reader_readers__reader_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reader_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderPublic"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reader_readers__reader_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reader_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_config__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponseModel"];
                };
            };
        };
    };
    message_stream_stream_get: {
        parameters: {
            query?: {
                stream_id?: string | null;
                reader_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_subscription_stream_subscription_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamRequestData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_stream_subscription_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamRequestData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    scan_event_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
