export enum EventAction {
    REDIRECT = 'REDIRECT',
    NEW_ITEM = 'NEW_ITEM',
    CONTAINER_SCAN = 'CONTAINER_SCAN',
    FORM_SCAN_ADD = 'FORM_SCAN_ADD',
    IDENTIFICATION = 'IDENTIFICATION',
    ALIVE = "ALIVE",
    ERROR = "ERROR",
    ELEMENT_UPDATE_READERS = "ELEMENT_UPDATE_READERS",
    ELEMENT_UPDATE_CONTAINER = "ELEMENT_UPDATE_CONTAINER",
    ELEMENT_UPDATE_USERS = "ELEMENT_UPDATE_USERS",
    ELEMENT_UPDATE_CATEGORIES = "ELEMENT_UPDATE_CATEGORIES",
}

export enum StreamEvent {
    SCAN = 'SCAN',
    SCAN_NEW = 'SCAN_NEW',
    IDENTIFICATION = 'IDENTIFICATION',
    ALIVE = 'ALIVE',
    ERROR = "ERROR",
    ELEMENT_UPDATE = "ELEMENT_UPDATE",
}
