services:
  devcontainer:
    #image: "mcr.microsoft.com/vscode/devcontainers/python:3.12-bookworm"
    build:
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    network_mode: host
    volumes:
      - ..:/workspaces:cached

  proxy:
    profiles:
      - "" # run a proxy in dev to serve images from /data
    depends_on: !reset []
    volumes:
      - ./.devcontainer/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/src/data:/data
    network_mode: host

  frontend:
    profiles:
      - skip
    deploy:
      replicas: 0

  backend:
    profiles:
      - skip
    deploy:
      replicas: 0

  db:
    ports:
      - 3306:3306
