services:
  devcontainer:
    #image: "mcr.microsoft.com/vscode/devcontainers/python:3.12-bookworm"
    build: 
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    network_mode: host
    volumes:
      - ..:/workspaces:cached
    privileged: true
  
  frontend:
    profiles:
      - skip
    deploy:
      replicas: 0
  backend:
    profiles:
      - skip
    deploy:
      replicas: 0
  db:
    container_name: mongo
    volumes:
      - ./.devcontainer/mongodb/init-mongo-db-with-items.js:/docker-entrypoint-initdb.d/init-mongo-db-with-items.js:ro
    ports:
      - 27017:27017

  # DEV Mqtt broker
  mqtt:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - ./.devcontainer/mqtt/mosquitto-data:/mosquitto/data
      - ./.devcontainer/mqtt/mosquitto-log:/mosquitto/log
      - ./.devcontainer/mqtt/mosquitto-conf:/mosquitto/config
    ports:
      - 1883:1883

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
