services:
  devcontainer:
    #image: "mcr.microsoft.com/vscode/devcontainers/python:3.12-bookworm"
    build:
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    network_mode: host
    volumes:
      - ..:/workspaces:cached

  wims:
    profiles:
      - skip
    deploy:
      replicas: 0

  db:
    ports:
      - 3306:3306
