server {
    listen 5005;
    server_name _;


    location /api/data/ {
        alias /data/;
        try_files $uri =404;
    }

    location /api/ {
        include uwsgi_params;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://localhost:8000;
    }

    location / {
        include uwsgi_params;
        proxy_pass http://localhost:5173;
    }
}
