GET http://localhost:5005/ws HTTP/1.1

###

GET http://localhost:8080/api/healthz  HTTP/1.1

###
GET http://localhost:8080/api/healthz/ready  HTTP/1.1

###
GET http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174000  HTTP/1.1

###
GET http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174008  HTTP/1.1

###
GET http://localhost:5005/users  HTTP/1.1

###
GET http://localhost:5005/items/321-321-321-321-321  HTTP/1.1

###
DELETE  http://localhost:5005/items/321-321-321-321-321  HTTP/1.1

###
DELETE  http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174004  HTTP/1.1

###
DELETE  http://localhost:5005/items/321-321-321-321-321  HTTP/1.1

###


GET http://localhost:5005/items  HTTP/1.1

###

GET http://localhost:5002/itemsreader=04-04-46-42-CD-66-81&rfid=123e4567-e89b-12d3-a456-426614174000 HTTP/1.1

###

GET http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174001  HTTP/1.1

###

GET http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174000/containers  HTTP/1.1

###
GET http://localhost:5005/items  HTTP/1.1
content-type: application/json

{
    "query":{
    "tags": ["tbd"],
    }
}
###

POST http://localhost:5005/items/backlog  HTTP/1.1
content-type: application/json

{
    "tag_uuid": "123e4567-e89b-12d3-a456-426614174120",
    "tags": ["tbd"],
    
}

###

PUT http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174120  HTTP/1.1
content-type: application/json

{
    "tag_uuid": "123e4567-e89b-12d3-a456-426614174120",
    "short_name": "sample_updated"
}
###

GET http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174120  HTTP/1.1

###
DELETE  http://localhost:5005/items/123e4567-e89b-12d3-a456-426614174120  HTTP/1.1

###

PUT http://localhost:5005/items  HTTP/1.1
content-type: application/json

{
    "short_name": "sample",
    "tag_uuid": "123e4567-e89b-12d3-a456-426614174000"
}

###

POST http://localhost:5005/queries
Content-Type: application/json

{
  "name": "Monthly Sales Report",
  "description": "Query to fetch sales data for the current month",
  "query": { "tag_uuid": "123e4567-e89b-12d3-a456-426614174000" }
}
###

POST http://localhost:5005/queries
Content-Type: application/json

{
  "name": "Item Backlog",
  "description": "Items that need to be edited",
  "query": { "tags": "tbd" }
}
###

GET http://localhost:5005/queries
###

PUT http://localhost:5005/queries/68875a0d3eb338f0eb394b92
Content-Type: application/json

{
     "name": "Updated Monthly Sales Report",
  "description": "Updated query to fetch sales data for the current month",
  "query": { "tag_uuid": "123e4567-e89b-12d3-a456-426614174000" }
}

### 

DELETE http://localhost:5005/queries/68875655b6ff3abd55480912


###
POST http://localhost:5005/scan  HTTP/1.1
content-type: application/json

{
    "reader_id": "04-04-46-42-CD-66-81",
    "tag_id": "123e4567-e89b-12d3-a456-426614174000"
}
###
POST http://localhost:5005/scan  HTTP/1.1
content-type: application/json

{
    "reader_id": "7450fa3d-d7cb-4208-8024-f9441f72374f",
    "tag_id": "123e4567-e89b-12d3-a456-426614174000"
}
###


###

GET http://localhost:5005/categories/10101500 HTTP/1.1

###
GET http://localhost:5005/categories/10101501/tree HTTP/1.1

###

GET http://localhost:5005/categories/search/?term=Electron HTTP/1.1
















