"""add user table

Revision ID: 034603580e05
Revises: 42fbaec66173
Create Date: 2026-02-22 20:19:27.650684

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '034603580e05'
down_revision: str | Sequence[str] | None = '42fbaec66173'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change',
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('diff_from_prev_version', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('ref')
    )
    op.create_table('item',
    sa.Column('tag_uuid', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=255), nullable=True),
    sa.Column('consumable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ai_generated', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('min_amount', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('cost_new', sa.Float(), nullable=True),
    sa.Column('acquisition_date', sa.Integer(), nullable=True),
    sa.Column('cost_used', sa.Float(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('manufacturing_date', sa.Integer(), nullable=True),
    sa.Column('upc', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('vendors', sa.JSON(), nullable=True),
    sa.Column('shop_url', sa.JSON(), nullable=True),
    sa.Column('size', sa.JSON(), nullable=True),
    sa.Column('documentation', sa.JSON(), nullable=True),
    sa.Column('related_items', sa.JSON(), nullable=True),
    sa.Column('container_tag_uuid', sa.String(length=255), nullable=True),
    sa.Column('is_container', sa.Boolean(), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('borrowed_by', sa.String(length=255), nullable=True),
    sa.Column('borrowed_at', sa.Integer(), nullable=True),
    sa.Column('borrowed_until', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('borrowed', sa.Boolean(), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('tag_uuid')
    )
    op.create_table('relation',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('related_tags', sa.JSON(), nullable=True),
    sa.Column('tag', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), server_default=sa.text('UUID()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('tag_uuids', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('relation')
    op.drop_table('item')
    op.drop_table('change')
    op.drop_table('category')
    # ### end Alembic commands ###
