"""add user table

Revision ID: 046da7d5cc95
Revises: 
Create Date: 2026-02-22 20:13:54.704919

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '046da7d5cc95'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
