"""add user table

Revision ID: 42fbaec66173
Revises: 046da7d5cc95
Create Date: 2026-02-22 20:15:41.996062

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '42fbaec66173'
down_revision: str | Sequence[str] | None = '046da7d5cc95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
