"""rename tag to code

Revision ID: 5cb7539b8194
Revises: b2c317ca3539
Create Date: 2026-04-30 15:31:01.157448

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cb7539b8194"
down_revision: str | Sequence[str] | None = "b2c317ca3539"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("code", sa.String(length=255), nullable=True))
    op.drop_index(op.f("ix_item_tag_uuid"), table_name="item")
    op.create_index(op.f("ix_item_code"), "item", ["code"], unique=True)
    op.drop_column("item", "tag_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("tag_uuid", mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f("ix_item_code"), table_name="item")
    op.create_index(op.f("ix_item_tag_uuid"), "item", ["tag_uuid"], unique=True)
    op.drop_column("item", "code")
    # ### end Alembic commands ###
