"""sth

Revision ID: 6418b97bd0fc
Revises: 99bfc98803ce
Create Date: 2026-05-11 17:14:50.728488

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6418b97bd0fc"
down_revision: str | Sequence[str] | None = "99bfc98803ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("code", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "code")
    # ### end Alembic commands ###
