"""add reader table

Revision ID: 6cf4c82a4ad5
Revises: 48a911feaeee
Create Date: 2026-02-28 22:27:41.040871

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cf4c82a4ad5'
down_revision: str | Sequence[str] | None = '48a911feaeee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('reader_id', sa.String(length=255), nullable=False),
    sa.Column('reader_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reader_reader_id'), 'reader', ['reader_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reader_reader_id'), table_name='reader')
    op.drop_table('reader')
    # ### end Alembic commands ###
