"""add last_scanned

Revision ID: 8466d909fc5e
Revises: 9b39f3359ea9
Create Date: 2026-05-18 19:43:04.508831

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8466d909fc5e"
down_revision: str | Sequence[str] | None = "9b39f3359ea9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("last_scanned", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "last_scanned")
    # ### end Alembic commands ###
