"""categories

Revision ID: 99bfc98803ce
Revises: 5cb7539b8194
Create Date: 2026-05-09 15:45:47.878478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99bfc98803ce"
down_revision: str | Sequence[str] | None = "5cb7539b8194"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category", "parent_id", existing_type=mysql.VARCHAR(length=255), type_=sa.Integer(), existing_nullable=True
    )
    op.create_foreign_key(None, "category", "category", ["parent_id"], ["id"])
    op.drop_column("item", "is_container")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item", sa.Column("is_container", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "category", type_="foreignkey")
    op.alter_column(
        "category", "parent_id", existing_type=sa.Integer(), type_=mysql.VARCHAR(length=255), existing_nullable=True
    )
    # ### end Alembic commands ###
