"""add is_container and is_borrowed

Revision ID: aa680d89db6c
Revises: c0b7da85048d
Create Date: 2026-06-01 23:11:53.536116

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa680d89db6c"
down_revision: str | Sequence[str] | None = "c0b7da85048d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "filetype",
        existing_type=mysql.ENUM("IMAGE", "MANUAL", "DRIVER", "FIRMWARE"),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "filetype",
        existing_type=sa.String(length=255),
        type_=mysql.ENUM("IMAGE", "MANUAL", "DRIVER", "FIRMWARE"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
