"""add files

Revision ID: b2c317ca3539
Revises: 6cf4c82a4ad5
Create Date: 2026-03-30 21:31:50.463547

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c317ca3539"
down_revision: str | Sequence[str] | None = "6cf4c82a4ad5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("asset_path", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("filetype", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_path"),
    )
    op.drop_table("url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column("created_at", mysql.DATETIME(), server_default=sa.text("current_timestamp()"), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), server_default=sa.text("current_timestamp()"), nullable=False),
        sa.Column("item_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mariadb_collate="utf8mb4_uca1400_ai_ci",
        mariadb_default_charset="utf8mb4",
        mariadb_engine="InnoDB",
    )
    op.drop_table("file")
    # ### end Alembic commands ###
