"""fix file types

Revision ID: c0b7da85048d
Revises: 8466d909fc5e
Create Date: 2026-05-20 18:48:44.876638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0b7da85048d"
down_revision: str | Sequence[str] | None = "8466d909fc5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "filetype",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Enum("IMAGE", "MANUAL", "DRIVER", "FIRMWARE", name="filetype"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "filetype",
        existing_type=sa.Enum("IMAGE", "MANUAL", "DRIVER", "FIRMWARE", name="filetype"),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
