---

wifi_networks:
- ssid: "Obi Wlan Kenobi"
  password: "ieyahCi9jiebeiNg"
- ssid: "fleaz-AP"
  password: "thepiratebay!"
- ssid: "homeautomation"
  password: "eV0ezTSykb4c85PI"
- ssid: "ventoux"
  password: "01733057450"

# Password for fallback AP
fallback_psk: "lKjxU3gheO0y"
