services:
  playwright:
    build: ./integration/
    volumes:
      - ./integration/playwright-results:/workspaces/integration/playwright-results
    environment:
      - CI=true
      - BACKEND_URL=http://backend:8000
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./vue_frontend
      args:
        VITE_API_URL: http://backend:8000

  backend:
    depends_on:
      db:
        condition: service_healthy

  db:
    volumes:
      # Reset the volume each restart
      - type: tmpfs
        target: /var/lib/mysql
        tmpfs:
          mode: 0777
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
